### ISSUE TITLE
Mark as Discontinue?

### ISSUE THREAD

**Issue by hyiso** [incendial/commit-lint#2]
Sorry to disturb, recently I have some work to lint commit messages  and found this one.

But this package is not in active development, so I created a new package [commitlint_cli](https://pub.dev/packages/commitlint_cli), covering most functionalities of npm package `commitlint`.

So I wonder whether it's possible to mark this package as `DISCONTINUED` in pub.dev? 

It's OK if not.

**Comment by incendial** [comment]
Nope, I plan to get back to it when I have time.
